version: '3.7'

services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    working_dir: /workdir/
    restart: on-failure
    depends_on:
      - backend
    ports: 80:80
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    working_dir: /workdir/
    restart: on-failure
    env_file:
      - backend.env
    ports:
      - "5000:5000"
    devices:
      - "/dev/video0:/dev/video0"